---
- hosts: localhost
  gather_facts: no
  vars:
    vcenter_server: "10.19.xx.xx"
    vcenter_user: "administrator@vsphere.local"
    vcenter_pass: "xxxxxx"
    datacenter_name: "vcenter-datacenter"
    cluster_name: "10.xx.xx.xx"
  tasks:
  - name: Provisioning VM From Template
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: test_vm
      template: vm-test-template
      datacenter: "{{ datacenter_name }}"
      folder: /{{ datacenter_name }}/vm
      cluster: "{{ cluster_name }}"
      datastore: "datastore01"
      networks:
      - name: VM Network
        ip: 10.xx.xx.xx
        netmask: 255.xx.xx.0
        gateway: 10.xx.xx.xx
        type: static
        dns_servers: 8.x.x.x
      customization:
        hostname: "test_vm"
        dns_servers:
        - 8.x.x.x
        - 8.x.x.x
      state: poweredon
      wait_for_ip_address: no
    delegate_to: localhost
