#Ansible script to fetch openshift cluster recource utilization
---
- hosts: localhost
  vars_files: vars.yml
  tasks: 
    - name: Connect to the Openshift cluster
      command: oc login -u {{ username }} -p {{ password }} https://{{ env_name }}:6443
      register: connection
    
    - name: Cluster connection status...
      debug:
        var: connection.stdout_lines
    
    - name: Displaying the node health status of {{ env_name}} openshift cluster
      command: oc adm top nodes
      register: node_status
    - name:
      debug:
        var: node_status.stdout_lines
  
#    - name: Displaying the resource details of {{ env_name}} openshift cluster
#      command: oc adm top nodes
#      register: node_resource_output
#    - name:
#      debug:
#        var: node_resource_output.stdout_lines

    - name: Displaying the project details of {{ env_name}} openshift cluster
      command: oc adm top pods --all-namespaces
      register: ns_resource_output
    - name:
      debug:
        var: ns_resource_output.stdout_lines
...
